on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

name: Check and Lint

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Linting
        run: cargo clippy

  check:
    name: Check & Test
    needs:
      - fmt
      - clippy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
          - build: macos
            os: macos-13-xlarge
          - build: windows
            os: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Check
        run: cargo check

      - name: Run Tests
        run: cargo test
